ogone_payment_form:
    pattern: /ogone/payment
    defaults: { _controller: PilotOgonePaymentBundle:DoctrinePayment:index }

ogone_payment_feedback:
    pattern: /ogone/payment-feedback
    defaults: { _controller: PilotOgonePaymentBundle:Payment:feedback }

ogone_template:
    pattern: /ogone/template/{twigPath}
    defaults: { _controller: PilotOgonePaymentBundle:Payment:renderTemplate }
